env:
  browser: true
  es2021: true

extends:
  - airbnb-base

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module

plugins:
  - '@typescript-eslint'

rules:
  import/no-unresolved: 0
  import/extensions: 0
  implicit-arrow-linebreak: 0
  import/prefer-default-export: 0
